### PR TITLE
Bug get reflect question parameter bug

### LINKED ISSUE #98: [Bug] Get reflect command crash program
**Describe the bug**
Command ```get reflect``` should be recognised as an invalid command but it it not caught and crashing the program. 

**To Reproduce**
1. Input ```reflect``` command to go to Self Reflection section
2. Input ```get reflect``` command 

**Expected behavior**
This command should be recognised as invalid and error message should be shown

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 10

### PR DESCRIPTION
**Pull request by wenxin-c**
Fixes #98 
Adding ```return;``` in catch block after a BadCommandException is caught to return back to main loop. In this way, the ```execute()```method will not continue executing.

### CODE REVIEW

File: src/main/java/wellnus/reflection/GetCommand.java [hunk 1]
```diff
@@ -131,7 +132,7 @@ public void validateCommand(HashMap<String, String> commandMap) throws BadComman
             throw new BadCommandException(INVALID_COMMAND_MSG);
         } else if (!commandMap.containsKey(COMMAND_KEYWORD)) {
             throw new BadCommandException(INVALID_COMMAND_MSG);
-        } else if (!commandMap.get(COMMAND_KEYWORD).equals(PAYLOAD)) {
+        } else if (!(commandMap.get(COMMAND_KEYWORD).equals(PAYLOAD))) {
```
Comment (nichyjt) [inline src/main/java/wellnus/reflection/GetCommand.java:135]: Is there really a need to wrap this in ()? For sake of standardization, this means ALL `!condition` should be rewritten as `!(condition)`

**Review by nichyjt — COMMENTED** [review]
One nit regarding standardization. For your consideration, please.

**Review by nichyjt — APPROVED** [review]
Thanks for the changes. LGTM!
