### PR TITLE
Fix parser off by one error

### LINKED ISSUE #32: [Bug] Inaccurate Payload Index
**Describe the bug**
Payload contains an additional term which is the command argument as the getPayload method loops from index 0.

**To Reproduce**
1. Utilize parser to get parsedInputs
2. Print argument and payload 
3. See that command argument is in payload as well

**Expected behavior**
Command argument to not be first string of payload

**Screenshots**
image

### PR DESCRIPTION
**Pull request by nichyjt**
This fixes #32.

### Changelog
Ignore the main command by starting from one

### CODE REVIEW

File: src/main/java/seedu/duke/command/CommandParser.java [hunk 1]
```diff
@@ -93,7 +93,8 @@ private String getArgumentFromCommand(String commandString) throws BadCommandExc
     private String getPayloadFromCommand(String commandString) {
         String[] words = commandString.split(PAYLOAD_DELIMITER);
         String payload = "";
-        for (int i = 0; i < words.length; ++i) {
+        // Ignore the first word (Main Command), so start from 1
+        for (int i = 1; i < words.length; ++i) {
```
Comment (YongbinWang) [inline src/main/java/seedu/duke/command/CommandParser.java:97]: Bug fixed to exclude main command and only include payload content.

**Review by YongbinWang — COMMENTED** [review]
Bug fixed for use. LGTM!

**Review by wenxin-c — APPROVED** [review]
LGTM!
