### PR TITLE
Fix bogus Exception in GamificationTokenizer

### LINKED ISSUE #322: [Bug] Gamif data always report error
**Describe the bug**
Once gamif file is touched, even tho  empty it, it will always print error message even if re-lanuch the program

**Expected behavior**

**Screenshots**
image

image

### PR DESCRIPTION
**Pull request by haoyangw**
Summary of changes:
-Detect and don't throw an Exception when the gamification data file is empty
-Reorder the execution flow of `MainManager` so that `WellNUS++` logo and greeting is always printed first
-Move `GamificationTokenizer` to the correct package

This fixes #322.

### CODE REVIEW

File: src/main/java/wellnus/gamification/util/GamificationStorage.java [hunk 1]
```diff
@@ -33,6 +34,10 @@ public GamificationData loadData() throws StorageException, TokenizerException {
         if (storage.checkFileExists(Storage.FILE_GAMIFICATION)) {
             ArrayList<String> tokenizedObjects = storage.loadData(Storage.FILE_GAMIFICATION);
             ArrayList<GamificationData> dataObjects = tokenizer.detokenize(tokenizedObjects);
+            int dataFileIsBlank = 0;
+            if (dataObjects.size() == dataFileIsBlank) {
+                return new GamificationData();
+            }
```
Comment (nichyjt) [inline src/main/java/wellnus/gamification/util/GamificationStorage.java:40]: Magic literals should be factored out

File: src/main/java/wellnus/gamification/util/GamificationStorage.java [hunk 2]
```diff
@@ -33,6 +34,10 @@ public GamificationData loadData() throws StorageException, TokenizerException {
...
             int dataObjectIndex = 0;
```
Comment (nichyjt) [inline src/main/java/wellnus/gamification/util/GamificationStorage.java:41]: Similarly, magic literals should be factored out

**Review by nichyjt — CHANGES_REQUESTED** [review]
Magic literal issue, other than that LGTM

**Review by nichyjt — APPROVED** [review]
LGTM!
