### PR TITLE
Fix certain atomic habit bugs found during PE-demo.

### LINKED ISSUE #244: [PE-D][Tester A] [Bug] Atomic Habit's top row of the ascii art is shifted one row to the right
Picture shown below

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: Aung-Phone-Naing/ped#8

### LINKED ISSUE #249: [PE-D][Tester B] Error message for wrong argument in Habits "update" command is misleading
When typing in the wrong keyword for the `update` command, it throws an error saying the command is wrong. This is slightly misleading as it was actually the named argument that was wrong.

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: Bawfen/ped#6

### PR DESCRIPTION
**Pull request by YongbinWang**
Fixed the following bugs:
1. Cosmetic bug with habit logo this fixes #244, #243 , #230 , #215 
2.  Fix update command this fixes #249 , #234 
3.  Fix invalid argument crash for AddCommand. Eg add --will crash

### CODE REVIEW

File: src/main/java/wellnus/atomichabit/command/AddCommand.java [hunk 1]
```diff
@@ -113,8 +113,7 @@ public void validateCommand(HashMap<String, String> arguments) throws BadCommand
         if (arguments.get(COMMAND_KEYWORD) != "") {
             throw new BadCommandException(AddCommand.COMMAND_INVALID_ARGUMENTS_MESSAGE);
         }
-        String name = arguments.get(AddCommand.COMMAND_NAME_ARGUMENT);
-        if (name.isEmpty()) {
+        if (!arguments.containsKey(AddCommand.COMMAND_NAME_ARGUMENT)) {
```
Comment (wenxin-c) [inline src/main/java/wellnus/atomichabit/command/AddCommand.java:116]: The previous check seems to catch the bug whereby the payload for name is empty, but the new one only checks whether there is name keyword.

**Review by wenxin-c — CHANGES_REQUESTED** [review]
One suggestion for you to consider, the rest is fine, after addressing then LGTM!!

**Review by wenxin-c — APPROVED** [review]
One suggestion for you to consider, the rest is fine, after addressing then LGTM!!
