### PR TITLE
Fix timer-related functionality bugs

### LINKED ISSUE #221: [PE-D][Tester B] Focus Timer is in an indeterminate state if you go home during a session
If the user returns home after starting a timer (which could be a valid user journey since the user may want to set a time to focus on reflection), and then returns to the Focus Timer, it is stuck in an indeterminate state where the user is unable to `check` or `start`. It may be confusing to the user as it says the "countdown has not started" when calling `check` but also tells them it has started when calling `start`.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Bawfen/ped#2

### LINKED ISSUE #225: [PE-D][Tester C] Timer Next Feature Bug
I tried typing next as one cycle ended. But it showed me "Break" instead of expected result "Task"... But the next cycle started as expected!

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: de-yi/ped#3

### PR DESCRIPTION
**Pull request by nichyjt**
This closes #225, closes #221, and cosmetic bug 2 under #251.

## Changelog
- Fixed state not resetting upon going `home` bugs
- Fix cosmetic bugs caused by not using `System.lineSeparator()`
- Major bug-prevention fix wrt cursors and stdin
  - When the timer starts printing the count from `10-1`, the cursor will disappear and no stdin will be recorded
  - Added flush stdin utility and other focus UI specific logic

### CODE REVIEW

File: src/main/java/wellnus/focus/feature/FocusUi.java [hunk 1]
```diff
@@ -0,0 +1,144 @@
...
+     *
+     * @param scanner Reference to the scanner being used by the UI
+     */
+    private void flushInput(Scanner scanner) {
+        // Implement a timeout to avoid hanging
+        long flushStartTime = System.currentTimeMillis();
+        while (scanner.hasNextLine()
+                && System.currentTimeMillis() - flushStartTime < 2000) {
+            // Discard extraneous input
+            scanner.nextLine();
```
Comment (YongbinWang) [inline src/main/java/wellnus/focus/feature/FocusUi.java:140]: Nice that you found a way to flush malicious user input during countdown. Can I check why the 2000ms is it just to have a time greater than 1000ms because of the printing duration?

File: src/main/java/wellnus/focus/feature/Countdown.java [hunk 2]
```diff
@@ -120,6 +127,19 @@ public void run() {
...
+     * Used to determine whether to print the seconds left and accept any user input.
+     *
+     * @return boolean Representing if the countdown timer is printing.
+     */
+    public boolean isCountdownPrinting() {
+        return (minutes == DEFAULT_STOP_TIME
+                && seconds <= COUNTDOWN_PRINT_START_TIME
+                && seconds != DEFAULT_STOP_TIME);
+    }
+
```
Comment (YongbinWang) [inline src/main/java/wellnus/focus/feature/Countdown.java:142]: Nice refactoring of 3 checks into a method.

**Review by YongbinWang — COMMENTED** [review]
Overall tested locally and both home command resetting the session and ignoring user input during 10 - 1 countdown works as advertised. Could not force an exception or crash the application as seen below, well done. LGTM!

image

File: src/main/java/wellnus/focus/feature/FocusUi.java (hunk 1 above)
Comment (nichyjt) [reply src/main/java/wellnus/focus/feature/FocusUi.java]: This is arbitrary and seemed to be stable when I tested. I've refactored this magic literal out and changed the value to `1000ms` which makes more intuitive sense since each print is in 1000ms interval

**Review by wenxin-c — APPROVED** [review]
Overall LGTM!!
